# Generated by Django 5.1.6 on 2025-07-27 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodect',
            new_name='Product',
        ),
    ]
